# Generated by Django 3.2.4 on 2021-06-20 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_auto_20210620_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticshitcount',
            name='hit_count',
            field=models.IntegerField(null=True),
        ),
    ]
