# Generated by Django 3.2.4 on 2021-06-20 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_alter_analyticshitcount_hit_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticshitcount',
            name='hit_count',
            field=models.IntegerField(default=0),
        ),
    ]
