# Generated by Django 3.2 on 2021-05-07 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0007_auto_20210507_2357"),
    ]

    operations = [
        migrations.AddField(
            model_name="musiclist",
            name="music_extension",
            field=models.CharField(default="", max_length=5),
        ),
    ]
