# Generated by Django 3.2 on 2021-05-24 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0009_musiclist_sample_rate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="musiclist",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
