# Generated by Django 3.2.4 on 2021-06-14 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0012_remove_musiclist_music_extension"),
    ]

    operations = [
        migrations.RenameField(
            model_name="musiclist",
            old_name="date",
            new_name="release_date",
        ),
    ]
