# Generated by Django 3.2.4 on 2021-06-14 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0014_rename_artist_musiclist_song_artist"),
    ]

    operations = [
        migrations.RenameField(
            model_name="musiclist",
            old_name="song_artist",
            new_name="artist",
        ),
        migrations.RenameField(
            model_name="musiclist",
            old_name="song_name",
            new_name="name",
        ),
    ]
