# Generated by Django 3.2.4 on 2021-06-14 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0015_auto_20210614_1856"),
    ]

    operations = [
        migrations.RenameField(
            model_name="musiclist",
            old_name="name",
            new_name="song_name",
        ),
    ]
