# Generated by Django 3.2.4 on 2021-06-17 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0016_rename_name_musiclist_song_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="musiclist",
            old_name="release_date",
            new_name="date",
        ),
    ]
