# Generated by Django 3.2.4 on 2021-06-17 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0017_rename_release_date_musiclist_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="musiclist",
            name="length",
            field=models.FloatField(),
        ),
    ]
