# Generated by Django 3.2.4 on 2021-06-17 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0018_alter_musiclist_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="musiclist",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
