# Generated by Django 3.2.4 on 2021-06-18 02:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("utility", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UserVolumeInput",
            new_name="UserVolumeInputCapture",
        ),
    ]
