# Generated by Django 3.2.4 on 2021-06-18 02:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0021_alter_musiclist_genre"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("utility", "0002_rename_uservolumeinput_uservolumeinputcapture"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPreviousSongCapture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "previous_song",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="upload.musiclist",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
