# Generated by Django 3.2.4 on 2021-06-21 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('upload', '0021_alter_musiclist_genre'),
        ('utility', '0003_userprevioussongcapture'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLastSongCapture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.FloatField()),
                ('last_song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.musiclist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('user',),
            },
        ),
    ]
