# Generated by Django 3.2 on 2021-05-07 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwordreseturl",
            name="url",
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
