# Generated by Django 3.2 on 2021-05-07 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_passwordreseturl_url"),
    ]

    operations = [
        migrations.RenameField(
            model_name="passwordreseturl",
            old_name="url",
            new_name="short_url",
        ),
    ]
