# Generated by Django 3.2 on 2021-05-07 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_rename_url_passwordreseturl_short_url"),
    ]

    operations = [
        migrations.RenameField(
            model_name="passwordreseturl",
            old_name="short_url",
            new_name="url",
        ),
    ]
