# Generated by Django 3.2.4 on 2021-06-15 13:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("user", "0005_userinput"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UserInput",
            new_name="UserVolumeInput",
        ),
    ]
