# Generated by Django 4.0a1 on 2021-10-01 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_capturetimestampmodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capturetimestampmodel',
            name='user',
        ),
        migrations.DeleteModel(
            name='CapturePreviousSongModel',
        ),
        migrations.DeleteModel(
            name='CaptureTimestampModel',
        ),
    ]
