# Generated by Django 3.2 on 2021-05-18 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("soundcore", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="librarygenerator",
            name="is_checked",
            field=models.BooleanField(default=False),
        ),
    ]
