# Generated by Django 3.2 on 2021-05-18 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0008_musiclist_music_extension"),
        ("soundcore", "0002_librarygenerator_is_checked"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="librarygenerator",
            name="is_checked",
        ),
        migrations.RemoveField(
            model_name="librarygenerator",
            name="musics",
        ),
        migrations.AddField(
            model_name="librarygenerator",
            name="musics",
            field=models.ForeignKey(
                default="1",
                on_delete=django.db.models.deletion.CASCADE,
                to="upload.musiclist",
            ),
            preserve_default=False,
        ),
    ]
