# Generated by Django 3.2.4 on 2021-06-18 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0021_alter_musiclist_genre"),
        ("soundcore", "0007_auto_20210519_1928"),
    ]

    operations = [
        migrations.AlterField(
            model_name="librarygenerator",
            name="musics",
            field=models.ManyToManyField(related_name="musics", to="upload.MusicList"),
        ),
    ]
