# Generated by Django 3.2.4 on 2021-06-19 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soundcore', '0008_alter_librarygenerator_musics'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='librarygenerator',
            options={'ordering': ('id',)},
        ),
    ]
