# Generated by Django 3.2.4 on 2021-06-20 05:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soundcore', '0009_alter_librarygenerator_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='librarygenerator',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='librarygenerator',
            name='last_modified',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='librarygenerator',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
