# Generated by Django 3.2.4 on 2021-06-20 05:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soundcore', '0010_auto_20210620_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarygenerator',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 20, 11, 1, 37, 99218)),
        ),
    ]
