# Generated by Django 3.2.4 on 2021-06-20 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soundcore', '0011_alter_librarygenerator_last_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarygenerator',
            name='last_modified',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
