# Generated by Django 3.2.6 on 2021-08-07 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(default='', max_length=1024, unique=True)),
                ('song_file', models.FileField(upload_to='songs/')),
                ('artist', models.CharField(default='', max_length=1024, null=True)),
                ('album', models.CharField(default='', max_length=1024, null=True)),
                ('album_art', models.FileField(upload_to='album_arts/')),
                ('date', models.CharField(default='', max_length=1024, null=True)),
                ('composer', models.CharField(default='', max_length=1024, null=True)),
                ('genre', models.CharField(default=None, max_length=1024, null=True)),
                ('lyricist', models.CharField(default='', max_length=1024, null=True)),
                ('bitrate', models.IntegerField(default=0, null=True)),
                ('length', models.FloatField()),
                ('sample_rate', models.IntegerField(default=0)),
                ('mime_type', models.CharField(default='', max_length=15)),
            ],
        ),
    ]
