# Generated by Django 4.0a1 on 2021-09-28 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_delete_uservolumeinputcapture'),
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Upload',
            new_name='UploadModel',
        ),
    ]
